### ISSUE TITLE
Link error in the email

### ISSUE THREAD

**Issue by funkycram** [staxDB/humhub-modules-announcements#3] opened 2018-01-16 16:36 UTC
Small bug :
![image](https://user-images.githubusercontent.com/23310825/35000033-97af948e-fae3-11e7-87d3-b38088705fa5.png)
If I click on this link I should arrive on the space, but the URL lakes the domain name.

**Comment by staxDB** [comment] 2018-01-16 20:33
Just tested it and you're right. But the issue is not my module, it's in all the notifications.  How's it going with you?

**Comment by funkycram** [comment] 2018-01-16 23:03
OK, thanks. Well, I checked a few other mails and the URL was `javascript:false'.
We are using your module quite a lot already and it works really fine !!

**Comment by Felli** [comment] 2018-08-03 05:03
Should be fixed here: https://github.com/humhub/humhub/commit/8921fe7d41ee44cb987bd2a1632f788a8fd71bd6

**Closed** 2019-01-12 12:20 UTC
Labels: wontfix
